# Generated by Django 5.2.6 on 2025-09-13 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('emission_factor', models.DecimalField(decimal_places=4, help_text='Default emission factor for this category', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(help_text='Type of activity (e.g., transportation, energy)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the activity')),
                ('carbon_amount', models.DecimalField(decimal_places=2, help_text='Carbon footprint in kg CO2', max_digits=10)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_footprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carbon Footprint',
                'verbose_name_plural': 'Carbon Footprints',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_goal', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly carbon goal in kg CO2', max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
