# Generated by Django 5.2.6 on 2025-09-13 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonRecord',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonSource',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('sourceType', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='carbonfootprint',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='carbon_goal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carbonrecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carbonsource'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='currentSources',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='api.carbonsource'),
        ),
        migrations.DeleteModel(
            name='CarbonFootprint',
        ),
    ]
